const app = getApp();
Page({
  data: { kinds: ['批量参保', '批量停保'], kindValues: ['enrollment', 'termination'], kindIndex: 0, enterprises: [], allPositions: [], positions: [], enterpriseIndex: 0, positionIndex: 0, rows: [], errors: [], fileName: '', filePath: '', loading: false },
  onLoad() { Promise.all([app.request('/enterprises'), app.request('/positions')]).then(([enterprises, allPositions]) => { const approved = allPositions.filter((item) => item.status === 'approved'), enterpriseId = (enterprises[0] && enterprises[0].id) || 0; this.setData({ enterprises, allPositions: approved, positions: approved.filter((item) => item.enterprise_id === enterpriseId) }); }); },
  kindChange(e) { this.setData({ kindIndex: Number(e.detail.value), errors: [], rows: [] }); },
  enterpriseChange(e) { const enterpriseIndex = Number(e.detail.value), enterprise = this.data.enterprises[enterpriseIndex], positions = this.data.allPositions.filter((item) => item.enterprise_id === enterprise.id); this.setData({ enterpriseIndex, positions, positionIndex: 0 }); },
  positionChange(e) { this.setData({ positionIndex: Number(e.detail.value) }); },
  template() { wx.showLoading({ title: '下载中' }); wx.downloadFile({ url: `${app.globalData.apiBase}/insured/import-template`, header: { Authorization: `Bearer ${app.globalData.token}` }, success: (res) => { wx.hideLoading(); if (res.statusCode === 200) wx.openDocument({ filePath: res.tempFilePath, showMenu: true }); else wx.showToast({ title: '模板下载失败', icon: 'none' }); }, fail: () => { wx.hideLoading(); wx.showToast({ title: '模板下载失败', icon: 'none' }); } }); },
  choose() { wx.chooseMessageFile({ count: 1, type: 'file', extension: ['csv', 'xlsx'], success: (res) => { const file = res.tempFiles[0], isCsv = file.name.toLowerCase().endsWith('.csv'); this.setData({ fileName: file.name, filePath: file.path, rows: [], errors: [] }); if (isCsv) wx.getFileSystemManager().readFile({ filePath: file.path, encoding: 'utf-8', success: (data) => this.parseCsv(data.data) }); } }); },
  parseCsv(text) { const lines = text.replace(/^\ufeff/, '').split(/\r?\n/).filter(Boolean), rows = [], errors = []; lines.slice(1).forEach((line, index) => { const cells = line.split(',').map((value) => value.trim().replace(/^"|"$/g, '')), row = { name: cells[0] || '', id_number: cells[1] || '', phone: cells[2] || '', effective_at: cells[3] || '', terminated_at: cells[4] || '' }; if (!row.id_number || (this.data.kindIndex === 0 && !row.name)) errors.push({ row: index + 2, message: '参保需姓名和身份证号，停保需身份证号' }); else rows.push(row); }); this.setData({ rows, errors }); },
  submit() { if (!this.data.filePath) { wx.showToast({ title: '请先选择电子表格', icon: 'none' }); return; } if (this.data.errors.length) { wx.showToast({ title: '请先修正表格错误', icon: 'none' }); return; } const enterprise = this.data.enterprises[this.data.enterpriseIndex], position = this.data.positions[this.data.positionIndex], kind = this.data.kindValues[this.data.kindIndex]; if (!enterprise || (kind === 'enrollment' && !position)) { wx.showToast({ title: '请选择单位和已审核岗位', icon: 'none' }); return; } this.setData({ loading: true }); app.upload('/insured/import-file', this.data.filePath, 'file', { kind, enterprise_id: String(enterprise.id), position_id: String((position && position.id) || 0) }).then((data) => { if (!data.ok) { this.setData({ errors: data.errors || [], loading: false }); return; } wx.showToast({ title: `成功 ${data.success} 人` }); this.setData({ fileName: '', filePath: '', rows: [], errors: [], loading: false }); }).catch(() => this.setData({ loading: false })); },
  onShareAppMessage() { return app.share('/pages/import/import', 'from=share'); }
});
