const app = getApp();
Page({
  data: { id: 0, item: null, checklist: [], timeline: [], documents: [], loading: true, uploadingType: '', submitting: false },
  onLoad(options) { this.setData({ id: Number(options.id) }); },
  onShow() { this.load(); },
  load() { return Promise.all([app.request('/claims', { silent: true }), app.request(`/claims/${this.data.id}/checklist`, { silent: true }), app.request(`/claims/${this.data.id}/timeline`, { silent: true }), app.request(`/claims/${this.data.id}/documents`, { silent: true })]).then(([claims, checklist, timeline, documents]) => { const item = claims.find((row) => row.id === this.data.id) || null; if (item) item.status_label = app.statusText(item.status); const mappedTimeline = timeline.map((row) => ({ ...row, status_label: app.statusText(row.node) })); this.setData({ item, checklist, timeline: mappedTimeline, documents, loading: false }); }).catch((error) => { this.setData({ loading: false }); wx.showToast({ title: error.message, icon: 'none' }); }); },
  upload(e) { const docType = e.currentTarget.dataset.type; wx.showActionSheet({ itemList: ['拍照 / 相册图片', '微信聊天文件（PDF/Word/Excel）'], success: (choice) => choice.tapIndex === 0 ? this.chooseImage(docType) : this.chooseFile(docType) }); },
  chooseImage(docType) { wx.chooseMedia({ count: 1, mediaType: ['image'], sourceType: ['album', 'camera'], sizeType: ['compressed'], success: (res) => this.doUpload(docType, res.tempFiles[0].tempFilePath) }); },
  chooseFile(docType) { wx.chooseMessageFile({ count: 1, type: 'file', extension: ['pdf', 'doc', 'docx', 'xls', 'xlsx', 'jpg', 'jpeg', 'png'], success: (res) => this.doUpload(docType, res.tempFiles[0].path) }); },
  doUpload(docType, path) { this.setData({ uploadingType: docType }); app.upload(`/claims/${this.data.id}/documents/upload`, path, 'file', { doc_type: docType }).then(() => { wx.showToast({ title: '材料已上传' }); this.setData({ uploadingType: '' }); this.load(); }).catch(() => this.setData({ uploadingType: '' })); },
  preview(e) { const url = e.currentTarget.dataset.url; if (!url) return; const fullUrl = /^https?:/.test(url) ? url : `${app.globalData.apiBase.replace(/\/api$/, '')}${url}`; wx.downloadFile({ url: fullUrl, header: { Authorization: `Bearer ${app.globalData.token}` }, success: (res) => wx.openDocument({ filePath: res.tempFilePath, showMenu: true }), fail: () => wx.showToast({ title: '材料打开失败', icon: 'none' }) }); },
  submit() { const missing = this.data.checklist.filter((item) => !item.uploaded); if (missing.length) { wx.showModal({ title: '材料尚未齐全', content: `还缺 ${missing.length} 项：${missing.map((item) => item.name).join('、')}`, showCancel: false }); return; } wx.showModal({ title: '提交保司审核', content: '提交后材料将进入平台初审和保司审核流程。', success: (res) => { if (!res.confirm) return; this.setData({ submitting: true }); app.request(`/claims/${this.data.id}/status`, { method: 'PATCH', data: { status: 'submitted', note: '企业已提交全部理赔材料' } }).then(() => { wx.showToast({ title: '已提交审核' }); this.setData({ submitting: false }); this.load(); }).catch(() => this.setData({ submitting: false })); } }); },
  onShareAppMessage() { return app.share('/pages/claim-detail/claim-detail', `id=${this.data.id}`); }
});
