const app = getApp();
Page({
  data: { id: 0, form: { actual_employer: '', actual_employer_id: null, name: '', occupation_class: '1-3类', plan_id: null }, employers: [], employerIndex: 0, classes: ['1-3类', '4类', '5类', '超5类'], classIndex: 0, plans: [], planIndex: 0, videos: [], item: null, saving: false, uploading: false, loading: true },
  onLoad(options) { this.setData({ id: Number(options.id || 0) }); this.load(); },
  load() {
    Promise.all([app.request('/actual-employers'), app.request('/plans'), this.data.id ? app.request('/positions') : Promise.resolve([]), this.data.id ? app.request(`/positions/${this.data.id}/videos`) : Promise.resolve([])])
      .then(([employers, plans, positions, videos]) => { const item = positions.find((row) => row.id === this.data.id) || null; const employerIndex = Math.max(0, employers.findIndex((row) => item && row.id === item.actual_employer_id)); const classIndex = Math.max(0, this.data.classes.indexOf(item ? item.occupation_class : '1-3类')); const planIndex = Math.max(0, plans.findIndex((row) => item && row.id === item.plan_id)); const form = item ? { actual_employer: item.actual_employer_name || item.actual_employer, actual_employer_id: item.actual_employer_id, name: item.name, occupation_class: item.occupation_class, plan_id: item.plan_id } : { actual_employer: (employers[0] && employers[0].name) || '', actual_employer_id: (employers[0] && employers[0].id) || null, name: '', occupation_class: '1-3类', plan_id: (plans[0] && plans[0].id) || null }; this.setData({ employers, plans, item, videos, employerIndex, classIndex, planIndex, form, loading: false }); }).catch(() => this.setData({ loading: false }));
  },
  input(e) { this.setData({ [`form.${e.currentTarget.dataset.key}`]: e.detail.value }); },
  employerChange(e) { const employerIndex = Number(e.detail.value), employer = this.data.employers[employerIndex]; this.setData({ employerIndex, 'form.actual_employer_id': employer.id, 'form.actual_employer': employer.name }); },
  classChange(e) { const classIndex = Number(e.detail.value); this.setData({ classIndex, 'form.occupation_class': this.data.classes[classIndex] }); },
  planChange(e) { const planIndex = Number(e.detail.value), plan = this.data.plans[planIndex]; this.setData({ planIndex, 'form.plan_id': plan.id }); },
  save() { const form = this.data.form; if (!form.name.trim() || !form.actual_employer_id) { wx.showToast({ title: '请填写岗位并选择用工单位', icon: 'none' }); return; } this.setData({ saving: true }); const request = app.request(this.data.id ? `/positions/${this.data.id}` : '/positions', { method: this.data.id ? 'PATCH' : 'POST', data: form }); request.then((item) => { wx.showToast({ title: this.data.id ? '已保存' : '已创建岗位' }); if (this.data.id) { this.setData({ saving: false }); this.load(); } else { this.setData({ id: item.id, saving: false }); this.load(); } }).catch(() => this.setData({ saving: false })); },
  uploadVideo() { if (!this.data.id) { wx.showToast({ title: '请先保存岗位', icon: 'none' }); return; } wx.chooseMedia({ count: 1, mediaType: ['video'], sourceType: ['album', 'camera'], maxDuration: 60, success: (res) => { this.setData({ uploading: true }); app.upload(`/positions/${this.data.id}/videos/upload`, res.tempFiles[0].tempFilePath).then(() => { wx.showToast({ title: '视频已提交' }); this.setData({ uploading: false }); this.load(); }).catch(() => this.setData({ uploading: false })); } }); }
});
