-- 为 20 个域各建一个最小权限用户 + schema。
-- 这是铁律 1(独立 schema、最小权限)的落地:跨域读表由数据库拒绝,不靠代码自觉。
-- 口令由环境变量注入,这里用占位符,由 entrypoint 替换。

CREATE SCHEMA IF NOT EXISTS identity;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='identity_user') THEN
  CREATE ROLE identity_user LOGIN PASSWORD ':IDENTITY_PW:';
END IF; END $$;
GRANT USAGE ON SCHEMA identity TO identity_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA identity GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO identity_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA identity GRANT USAGE, SELECT ON SEQUENCES TO identity_user;

CREATE SCHEMA IF NOT EXISTS org;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='org_user') THEN
  CREATE ROLE org_user LOGIN PASSWORD ':ORG_PW:';
END IF; END $$;
GRANT USAGE ON SCHEMA org TO org_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA org GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO org_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA org GRANT USAGE, SELECT ON SEQUENCES TO org_user;

CREATE SCHEMA IF NOT EXISTS job;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='job_user') THEN
  CREATE ROLE job_user LOGIN PASSWORD ':JOB_PW:';
END IF; END $$;
GRANT USAGE ON SCHEMA job TO job_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA job GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO job_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA job GRANT USAGE, SELECT ON SEQUENCES TO job_user;

CREATE SCHEMA IF NOT EXISTS engagement;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='engagement_user') THEN
  CREATE ROLE engagement_user LOGIN PASSWORD ':ENGAGEMENT_PW:';
END IF; END $$;
GRANT USAGE ON SCHEMA engagement TO engagement_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA engagement GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO engagement_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA engagement GRANT USAGE, SELECT ON SEQUENCES TO engagement_user;

CREATE SCHEMA IF NOT EXISTS settlement;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='settlement_user') THEN
  CREATE ROLE settlement_user LOGIN PASSWORD ':SETTLEMENT_PW:';
END IF; END $$;
GRANT USAGE ON SCHEMA settlement TO settlement_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA settlement GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO settlement_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA settlement GRANT USAGE, SELECT ON SEQUENCES TO settlement_user;

CREATE SCHEMA IF NOT EXISTS fund;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='fund_user') THEN
  CREATE ROLE fund_user LOGIN PASSWORD ':FUND_PW:';
END IF; END $$;
GRANT USAGE ON SCHEMA fund TO fund_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA fund GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO fund_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA fund GRANT USAGE, SELECT ON SEQUENCES TO fund_user;

CREATE SCHEMA IF NOT EXISTS broker;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='broker_user') THEN
  CREATE ROLE broker_user LOGIN PASSWORD ':BROKER_PW:';
END IF; END $$;
GRANT USAGE ON SCHEMA broker TO broker_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA broker GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO broker_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA broker GRANT USAGE, SELECT ON SEQUENCES TO broker_user;

CREATE SCHEMA IF NOT EXISTS profile;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='profile_user') THEN
  CREATE ROLE profile_user LOGIN PASSWORD ':PROFILE_PW:';
END IF; END $$;
GRANT USAGE ON SCHEMA profile TO profile_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA profile GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO profile_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA profile GRANT USAGE, SELECT ON SEQUENCES TO profile_user;

CREATE SCHEMA IF NOT EXISTS matching;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='matching_user') THEN
  CREATE ROLE matching_user LOGIN PASSWORD ':MATCHING_PW:';
END IF; END $$;
GRANT USAGE ON SCHEMA matching TO matching_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA matching GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO matching_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA matching GRANT USAGE, SELECT ON SEQUENCES TO matching_user;

CREATE SCHEMA IF NOT EXISTS review;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='review_user') THEN
  CREATE ROLE review_user LOGIN PASSWORD ':REVIEW_PW:';
END IF; END $$;
GRANT USAGE ON SCHEMA review TO review_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA review GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO review_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA review GRANT USAGE, SELECT ON SEQUENCES TO review_user;

CREATE SCHEMA IF NOT EXISTS agreement;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='agreement_user') THEN
  CREATE ROLE agreement_user LOGIN PASSWORD ':AGREEMENT_PW:';
END IF; END $$;
GRANT USAGE ON SCHEMA agreement TO agreement_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA agreement GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO agreement_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA agreement GRANT USAGE, SELECT ON SEQUENCES TO agreement_user;

CREATE SCHEMA IF NOT EXISTS voice;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='voice_user') THEN
  CREATE ROLE voice_user LOGIN PASSWORD ':VOICE_PW:';
END IF; END $$;
GRANT USAGE ON SCHEMA voice TO voice_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA voice GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO voice_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA voice GRANT USAGE, SELECT ON SEQUENCES TO voice_user;

CREATE SCHEMA IF NOT EXISTS talent;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='talent_user') THEN
  CREATE ROLE talent_user LOGIN PASSWORD ':TALENT_PW:';
END IF; END $$;
GRANT USAGE ON SCHEMA talent TO talent_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA talent GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO talent_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA talent GRANT USAGE, SELECT ON SEQUENCES TO talent_user;

CREATE SCHEMA IF NOT EXISTS notification;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='notification_user') THEN
  CREATE ROLE notification_user LOGIN PASSWORD ':NOTIFICATION_PW:';
END IF; END $$;
GRANT USAGE ON SCHEMA notification TO notification_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA notification GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO notification_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA notification GRANT USAGE, SELECT ON SEQUENCES TO notification_user;

CREATE SCHEMA IF NOT EXISTS content;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='content_user') THEN
  CREATE ROLE content_user LOGIN PASSWORD ':CONTENT_PW:';
END IF; END $$;
GRANT USAGE ON SCHEMA content TO content_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA content GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO content_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA content GRANT USAGE, SELECT ON SEQUENCES TO content_user;

CREATE SCHEMA IF NOT EXISTS collab;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='collab_user') THEN
  CREATE ROLE collab_user LOGIN PASSWORD ':COLLAB_PW:';
END IF; END $$;
GRANT USAGE ON SCHEMA collab TO collab_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA collab GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO collab_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA collab GRANT USAGE, SELECT ON SEQUENCES TO collab_user;

CREATE SCHEMA IF NOT EXISTS reimbursement;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='reimbursement_user') THEN
  CREATE ROLE reimbursement_user LOGIN PASSWORD ':REIMBURSEMENT_PW:';
END IF; END $$;
GRANT USAGE ON SCHEMA reimbursement TO reimbursement_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA reimbursement GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO reimbursement_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA reimbursement GRANT USAGE, SELECT ON SEQUENCES TO reimbursement_user;

CREATE SCHEMA IF NOT EXISTS mall;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='mall_user') THEN
  CREATE ROLE mall_user LOGIN PASSWORD ':MALL_PW:';
END IF; END $$;
GRANT USAGE ON SCHEMA mall TO mall_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA mall GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO mall_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA mall GRANT USAGE, SELECT ON SEQUENCES TO mall_user;

CREATE SCHEMA IF NOT EXISTS ops;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='ops_user') THEN
  CREATE ROLE ops_user LOGIN PASSWORD ':OPS_PW:';
END IF; END $$;
GRANT USAGE ON SCHEMA ops TO ops_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA ops GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ops_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA ops GRANT USAGE, SELECT ON SEQUENCES TO ops_user;

CREATE SCHEMA IF NOT EXISTS reporting;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='reporting_user') THEN
  CREATE ROLE reporting_user LOGIN PASSWORD ':REPORTING_PW:';
END IF; END $$;
GRANT USAGE ON SCHEMA reporting TO reporting_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA reporting GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO reporting_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA reporting GRANT USAGE, SELECT ON SEQUENCES TO reporting_user;

CREATE SCHEMA IF NOT EXISTS attendance;
DO $$ BEGIN IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname='attendance_user') THEN
  CREATE ROLE attendance_user LOGIN PASSWORD ':ATTENDANCE_PW:';
END IF; END $$;
GRANT USAGE ON SCHEMA attendance TO attendance_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA attendance GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO attendance_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA attendance GRANT USAGE, SELECT ON SEQUENCES TO attendance_user;
