"""baseline schema

Revision ID: 9536dc0da3f7
Revises: 
Create Date: 2026-07-13 10:10:18.017220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9536dc0da3f7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('credit_code', sa.String(length=40), nullable=False),
    sa.Column('contact', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=True),
    sa.Column('premium_balance', sa.Float(), nullable=False),
    sa.Column('usage_balance', sa.Float(), nullable=False),
    sa.Column('usage_fee_daily', sa.Float(), nullable=False),
    sa.Column('alert_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprises_name'), 'enterprises', ['name'], unique=False)
    op.create_table('insurance_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('insurer', sa.String(length=100), nullable=False),
    sa.Column('insurer_email', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('coverage', sa.Text(), nullable=False),
    sa.Column('occupation_classes', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('commission_rate', sa.Float(), nullable=False),
    sa.Column('profit_amount', sa.Float(), nullable=False),
    sa.Column('payment_mode', sa.String(length=30), nullable=False),
    sa.Column('billing_mode', sa.String(length=20), nullable=False),
    sa.Column('effective_mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('actual_employers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('credit_code', sa.String(length=40), nullable=False),
    sa.Column('contact', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('markup_amount', sa.Float(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['insurance_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('object_id', sa.String(length=80), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('enrollment_emails',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('recipient', sa.String(length=160), nullable=False),
    sa.Column('filename', sa.String(length=160), nullable=False),
    sa.Column('people_count', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['insurance_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('tax_no', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=100), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('account', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_table('plan_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('occupation_class', sa.String(length=30), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('coverage', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['insurance_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_no', sa.String(length=80), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('premium', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('start_date', sa.String(length=20), nullable=False),
    sa.Column('end_date', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['insurance_plans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_no')
    )
    op.create_table('work_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('actual_employer_id', sa.Integer(), nullable=True),
    sa.Column('actual_employer', sa.String(length=160), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('occupation_class', sa.String(length=30), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actual_employer_id'], ['actual_employers.id'], ),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['insurance_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('insured_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('id_number', sa.String(length=40), nullable=False),
    sa.Column('occupation', sa.String(length=80), nullable=False),
    sa.Column('occupation_class', sa.String(length=20), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['work_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['work_positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enterprise_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('claim_no', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('accident_at', sa.String(length=30), nullable=False),
    sa.Column('accident_place', sa.String(length=200), nullable=False),
    sa.Column('accident_type', sa.String(length=60), nullable=False),
    sa.Column('hospital', sa.String(length=160), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('medical_cost', sa.Float(), nullable=False),
    sa.Column('contact_name', sa.String(length=80), nullable=False),
    sa.Column('contact_phone', sa.String(length=30), nullable=False),
    sa.Column('insurer_report_no', sa.String(length=100), nullable=False),
    sa.Column('current_handler', sa.String(length=80), nullable=False),
    sa.Column('deadline', sa.String(length=30), nullable=False),
    sa.Column('approved_amount', sa.Float(), nullable=False),
    sa.Column('paid_at', sa.String(length=30), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('sla_deadline', sa.String(length=30), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enterprise_id'], ['enterprises.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['insured_people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('claim_no')
    )
    op.create_table('claim_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('doc_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('review_note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_timelines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('claim_id', sa.Integer(), nullable=False),
    sa.Column('node', sa.String(length=40), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('operator', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('claim_timelines')
    op.drop_table('claim_documents')
    op.drop_table('claims')
    op.drop_table('position_videos')
    op.drop_table('insured_people')
    op.drop_table('work_positions')
    op.drop_table('policies')
    op.drop_table('plan_tiers')
    op.drop_table('payment_records')
    op.drop_table('invoices')
    op.drop_table('enrollment_emails')
    op.drop_table('audit_logs')
    op.drop_table('agent_commissions')
    op.drop_table('actual_employers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('insurance_plans')
    op.drop_index(op.f('ix_enterprises_name'), table_name='enterprises')
    op.drop_table('enterprises')
    # ### end Alembic commands ###
