const app = getApp();
Page({
  data: { enterprises: [], allPeople: [], people: [], enterpriseIndex: 0, personIndex: 0, accidentTypes: ['工作场所事故', '上下班交通事故', '职业病', '突发疾病', '其他工伤事故'], typeIndex: 0, form: { accident_date: '', accident_time: '', accident_place: '', accident_type: '工作场所事故', hospital: '', diagnosis: '', contact_name: '', contact_phone: '', amount: '0', description: '' }, saving: false, preferredPersonId: 0 },
  onLoad(options) { const preferredPersonId = Number(options.personId || 0); this.setData({ preferredPersonId }); Promise.all([app.request('/enterprises'), app.request('/insured')]).then(([enterprises, people]) => { const enterpriseId = (enterprises[0] && enterprises[0].id) || 0, filtered = people.filter((item) => item.enterprise_id === enterpriseId), personIndex = Math.max(0, filtered.findIndex((item) => item.id === preferredPersonId)); this.setData({ enterprises, allPeople: people, people: filtered, personIndex }); }); },
  input(e) { this.setData({ [`form.${e.currentTarget.dataset.key}`]: e.detail.value }); },
  enterpriseChange(e) { const enterpriseIndex = Number(e.detail.value), enterprise = this.data.enterprises[enterpriseIndex], people = this.data.allPeople.filter((item) => item.enterprise_id === enterprise.id); this.setData({ enterpriseIndex, people, personIndex: 0 }); },
  personChange(e) { this.setData({ personIndex: Number(e.detail.value) }); },
  typeChange(e) { const typeIndex = Number(e.detail.value); this.setData({ typeIndex, 'form.accident_type': this.data.accidentTypes[typeIndex] }); },
  dateChange(e) { this.setData({ 'form.accident_date': e.detail.value }); },
  timeChange(e) { this.setData({ 'form.accident_time': e.detail.value }); },
  save() { const enterprise = this.data.enterprises[this.data.enterpriseIndex], person = this.data.people[this.data.personIndex], form = this.data.form; if (!enterprise || !person || !form.accident_date || !form.accident_place.trim() || !form.description.trim()) { wx.showToast({ title: '请填写事故必填信息', icon: 'none' }); return; } this.setData({ saving: true }); app.request('/claims', { method: 'POST', data: { enterprise_id: enterprise.id, person_id: person.id, accident_at: `${form.accident_date} ${form.accident_time || '00:00'}`, accident_place: form.accident_place, accident_type: form.accident_type, hospital: form.hospital, diagnosis: form.diagnosis, contact_name: form.contact_name, contact_phone: form.contact_phone, amount: Number(form.amount || 0), description: form.description } }).then(() => { wx.showToast({ title: '报案成功' }); setTimeout(() => wx.navigateBack(), 500); }).catch(() => this.setData({ saving: false })); }
});
