-- Baseline schema for the Java/MyBatis port of 响帮帮无忧保.
-- Consolidates the four Alembic migrations from the Python backend
-- (baseline + ledger_entries + users.session_version + policy_members)
-- into a single end-state schema, since this is a greenfield rewrite with
-- no migration history to preserve. Written to run unmodified on both H2
-- (MODE=PostgreSQL, local dev) and PostgreSQL (production) — see
-- application.yml profiles.

CREATE TABLE enterprises (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(160) NOT NULL,
    kind VARCHAR(30) NOT NULL DEFAULT '企业',
    credit_code VARCHAR(40) NOT NULL DEFAULT '',
    contact VARCHAR(80) NOT NULL DEFAULT '',
    phone VARCHAR(30) NOT NULL DEFAULT '',
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    agent_id INTEGER,
    premium_balance DOUBLE PRECISION NOT NULL DEFAULT 0,
    usage_balance DOUBLE PRECISION NOT NULL DEFAULT 0,
    usage_fee_daily DOUBLE PRECISION NOT NULL DEFAULT 0.1,
    alert_days INTEGER NOT NULL DEFAULT 3,
    created_at TIMESTAMP NOT NULL
);
CREATE INDEX ix_enterprises_name ON enterprises (name);

CREATE TABLE insurance_plans (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    insurer VARCHAR(100) NOT NULL,
    insurer_email VARCHAR(160) NOT NULL DEFAULT '',
    name VARCHAR(160) NOT NULL,
    coverage TEXT NOT NULL DEFAULT '',
    occupation_classes VARCHAR(100) NOT NULL DEFAULT '1-4类',
    price DOUBLE PRECISION NOT NULL DEFAULT 0,
    commission_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    profit_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    payment_mode VARCHAR(30) NOT NULL DEFAULT '企业直投',
    billing_mode VARCHAR(20) NOT NULL DEFAULT 'monthly',
    effective_mode VARCHAR(20) NOT NULL DEFAULT 'next_day',
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(80) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    name VARCHAR(80) NOT NULL,
    role VARCHAR(40) NOT NULL,
    enterprise_id INTEGER,
    phone VARCHAR(30) NOT NULL DEFAULT '',
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    is_owner BOOLEAN NOT NULL DEFAULT FALSE,
    session_version INTEGER NOT NULL DEFAULT 1,
    created_at TIMESTAMP NOT NULL
);
CREATE UNIQUE INDEX ix_users_username ON users (username);

CREATE TABLE actual_employers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_id INTEGER NOT NULL REFERENCES enterprises(id),
    name VARCHAR(160) NOT NULL,
    credit_code VARCHAR(40) NOT NULL DEFAULT '',
    contact VARCHAR(80) NOT NULL DEFAULT '',
    phone VARCHAR(30) NOT NULL DEFAULT '',
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE agent_commissions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agent_id INTEGER NOT NULL REFERENCES users(id),
    enterprise_id INTEGER NOT NULL REFERENCES enterprises(id),
    plan_id INTEGER NOT NULL REFERENCES insurance_plans(id),
    rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    mode VARCHAR(20) NOT NULL DEFAULT 'rebate',
    markup_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    sale_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE audit_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    action VARCHAR(100) NOT NULL,
    object_type VARCHAR(80) NOT NULL,
    object_id VARCHAR(80) NOT NULL,
    detail TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE enrollment_emails (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_id INTEGER NOT NULL REFERENCES enterprises(id),
    plan_id INTEGER NOT NULL REFERENCES insurance_plans(id),
    kind VARCHAR(20) NOT NULL,
    recipient VARCHAR(160) NOT NULL DEFAULT '',
    filename VARCHAR(160) NOT NULL DEFAULT '',
    people_count INTEGER NOT NULL DEFAULT 0,
    request_id VARCHAR(100) NOT NULL DEFAULT '',
    status VARCHAR(30) NOT NULL DEFAULT 'sent',
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE invoices (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_id INTEGER NOT NULL REFERENCES enterprises(id),
    account VARCHAR(20) NOT NULL,
    amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    title VARCHAR(160) NOT NULL DEFAULT '',
    tax_no VARCHAR(40) NOT NULL DEFAULT '',
    email VARCHAR(160) NOT NULL DEFAULT '',
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE payment_records (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_no VARCHAR(100) NOT NULL UNIQUE,
    enterprise_id INTEGER NOT NULL REFERENCES enterprises(id),
    account VARCHAR(20) NOT NULL,
    amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    provider VARCHAR(60) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE plan_tiers (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    plan_id INTEGER NOT NULL REFERENCES insurance_plans(id),
    occupation_class VARCHAR(30) NOT NULL,
    price DOUBLE PRECISION NOT NULL DEFAULT 0,
    coverage TEXT NOT NULL DEFAULT '',
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE policies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_no VARCHAR(80) NOT NULL UNIQUE,
    enterprise_id INTEGER NOT NULL REFERENCES enterprises(id),
    plan_id INTEGER NOT NULL REFERENCES insurance_plans(id),
    premium DOUBLE PRECISION NOT NULL DEFAULT 0,
    status VARCHAR(30) NOT NULL DEFAULT 'active',
    start_date VARCHAR(20) NOT NULL DEFAULT '',
    end_date VARCHAR(20) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE work_positions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_id INTEGER NOT NULL REFERENCES enterprises(id),
    actual_employer_id INTEGER REFERENCES actual_employers(id),
    actual_employer VARCHAR(160) NOT NULL DEFAULT '',
    name VARCHAR(100) NOT NULL,
    occupation_class VARCHAR(30) NOT NULL DEFAULT '待定',
    plan_id INTEGER REFERENCES insurance_plans(id),
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE insured_people (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_id INTEGER NOT NULL REFERENCES enterprises(id),
    name VARCHAR(80) NOT NULL,
    phone VARCHAR(30) NOT NULL DEFAULT '',
    id_number VARCHAR(40) NOT NULL DEFAULT '',
    occupation VARCHAR(80) NOT NULL DEFAULT '',
    occupation_class VARCHAR(20) NOT NULL DEFAULT '3类',
    position_id INTEGER REFERENCES work_positions(id),
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    policy_id INTEGER REFERENCES policies(id),
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE position_videos (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position_id INTEGER NOT NULL REFERENCES work_positions(id),
    name VARCHAR(160) NOT NULL,
    url TEXT NOT NULL DEFAULT '',
    status VARCHAR(30) NOT NULL DEFAULT 'pending',
    review_note TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE claims (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_id INTEGER NOT NULL REFERENCES enterprises(id),
    person_id INTEGER NOT NULL REFERENCES insured_people(id),
    claim_no VARCHAR(80) NOT NULL UNIQUE,
    description TEXT NOT NULL DEFAULT '',
    status VARCHAR(30) NOT NULL DEFAULT 'reported',
    amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    accident_at VARCHAR(30) NOT NULL DEFAULT '',
    accident_place VARCHAR(200) NOT NULL DEFAULT '',
    accident_type VARCHAR(60) NOT NULL DEFAULT '工伤事故',
    hospital VARCHAR(160) NOT NULL DEFAULT '',
    diagnosis TEXT NOT NULL DEFAULT '',
    medical_cost DOUBLE PRECISION NOT NULL DEFAULT 0,
    contact_name VARCHAR(80) NOT NULL DEFAULT '',
    contact_phone VARCHAR(30) NOT NULL DEFAULT '',
    insurer_report_no VARCHAR(100) NOT NULL DEFAULT '',
    current_handler VARCHAR(80) NOT NULL DEFAULT '',
    deadline VARCHAR(30) NOT NULL DEFAULT '',
    approved_amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    paid_at VARCHAR(30) NOT NULL DEFAULT '',
    rejection_reason TEXT NOT NULL DEFAULT '',
    review_note TEXT NOT NULL DEFAULT '',
    sla_deadline VARCHAR(30) NOT NULL DEFAULT '',
    risk_level VARCHAR(20) NOT NULL DEFAULT 'normal',
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE claim_documents (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id INTEGER NOT NULL REFERENCES claims(id),
    name VARCHAR(160) NOT NULL,
    url TEXT NOT NULL DEFAULT '',
    doc_type VARCHAR(40) NOT NULL DEFAULT 'other',
    status VARCHAR(30) NOT NULL DEFAULT 'uploaded',
    review_note TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE claim_timelines (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    claim_id INTEGER NOT NULL REFERENCES claims(id),
    node VARCHAR(40) NOT NULL,
    action VARCHAR(100) NOT NULL,
    note TEXT NOT NULL DEFAULT '',
    operator VARCHAR(80) NOT NULL DEFAULT '',
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE ledger_entries (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_id INTEGER NOT NULL REFERENCES enterprises(id),
    account VARCHAR(20) NOT NULL,
    direction VARCHAR(10) NOT NULL,
    amount NUMERIC(18,2) NOT NULL,
    business_type VARCHAR(40) NOT NULL,
    business_id VARCHAR(80) NOT NULL DEFAULT '',
    idempotency_key VARCHAR(120) NOT NULL DEFAULT '',
    created_by INTEGER REFERENCES users(id),
    occurred_at TIMESTAMP NOT NULL
);
CREATE INDEX ix_ledger_entries_idempotency_key ON ledger_entries (idempotency_key);

CREATE TABLE policy_members (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    policy_id INTEGER NOT NULL REFERENCES policies(id),
    person_id INTEGER NOT NULL REFERENCES insured_people(id),
    rate_snapshot_json TEXT NOT NULL DEFAULT '',
    effective_at TIMESTAMP NOT NULL,
    terminated_at TIMESTAMP,
    endorsement_no VARCHAR(80) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL
);
CREATE INDEX ix_policy_members_person_id ON policy_members (person_id);
