CREATE TABLE insurer_accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR(100) NOT NULL DEFAULT '',
    bank_name VARCHAR(100) NOT NULL DEFAULT '',
    account_no VARCHAR(60) NOT NULL DEFAULT '',
    account_holder VARCHAR(100) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE insurer_account_links (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    insurer VARCHAR(100) NOT NULL,
    account_id INTEGER NOT NULL REFERENCES insurer_accounts(id),
    created_at TIMESTAMP NOT NULL
);
CREATE INDEX ix_insurer_account_links_insurer ON insurer_account_links (insurer);

CREATE TABLE enterprise_premium_accounts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_id INTEGER NOT NULL REFERENCES enterprises(id),
    account_id INTEGER NOT NULL REFERENCES insurer_accounts(id),
    balance DOUBLE PRECISION NOT NULL DEFAULT 0
);
CREATE INDEX ix_enterprise_premium_accounts_enterprise ON enterprise_premium_accounts (enterprise_id);

CREATE TABLE recharge_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    enterprise_id INTEGER NOT NULL REFERENCES enterprises(id),
    account_type VARCHAR(20) NOT NULL,
    insurer VARCHAR(100),
    account_id INTEGER REFERENCES insurer_accounts(id),
    amount DOUBLE PRECISION NOT NULL DEFAULT 0,
    receipt_file_url VARCHAR(255) NOT NULL DEFAULT '',
    status VARCHAR(20) NOT NULL DEFAULT 'pending',
    reject_reason VARCHAR(255) NOT NULL DEFAULT '',
    created_by INTEGER NOT NULL REFERENCES users(id),
    confirmed_by INTEGER REFERENCES users(id),
    confirmed_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL
);
CREATE INDEX ix_recharge_requests_enterprise ON recharge_requests (enterprise_id);
CREATE INDEX ix_recharge_requests_status ON recharge_requests (status);

ALTER TABLE ledger_entries ADD COLUMN account_id INTEGER REFERENCES insurer_accounts(id);
